project_name: GoMPing
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: GoMPing
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto